### PR TITLE
small cleanup, make code a bit more readable

### PR DESCRIPTION
**Pull request by KrahJohlito**
array sizes are probably still unnecessarily big..

## Pull Request checklist

Note: these are not necessarily requirements

- [ ] I reformatted the code with clang-format
- [ ] I checked to make sure my submission worked
- [x] I am the author of submission or have permission from the original author
- [ ] Requires update of the PS2SDK
- [ ] Requires update of the gsKit
- [ ] Others (please specify below)

## Pull Request description
Just looks a little nicer

### CODE REVIEW

**Comment by Tiagofanhais** [comment]
stop workink this Opl launcher  after changes made

**Comment by israpps** [comment]
> stop workink this Opl launcher after changes made

Are you sure?
It kicks back to browser?
Freezes con black screen?
Goes to OPL without launching game?


Are you sure the KELF was properly encrypted?

**Comment by Tiagofanhais** [comment]
black screen with this new opl launcher
with older one works with 336 bytes
[boot.zip](https://github.com/ps2homebrew/OPL-Launcher/files/7035351/boot.zip)

**Comment by KrahJohlito** [comment]
> black screen with this new opl launcher with older one works with 336 bytes [boot.zip](https://github.com/ps2homebrew/OPL-Launcher/files/7035351/boot.zip)

lol so, I only just saw this report.. I don't have time to debug and I don't see any reason for this so I just reverted. Thank you

**Pull request merged**
