### PR TITLE
Patch

### LINKED ISSUE #5: [ISSUE] Some partitions aren’t being read
There seems to be a problem with some partitions not being read properly.. this is what is causing the white screen issues.

PP.SLES-50498.HDL.Grandia_2

Is one confirmed by Berion on his setup that isn’t working.. strangely though OPL boots which means hddGetHdlInfo() is still returning >= 0 …but it sends mostly blank args.. as seen in a debug build he tested for me… further investigation required.

### PR DESCRIPTION
**Pull request by KrahJohlito**
## Pull Request checklist

Note: these are not necessarily requirements

- [ ] I reformatted the code with clang-format
- [x] I checked to make sure my submission worked
- [x] I am the author of submission or have permission from the original author
- [ ] Requires update of the PS2SDK
- [ ] Requires update of the gsKit
- [ ] Others (please specify below)

## Pull Request description
Ok this is confirmed to fix #5, previously it didn't work due to the fileXio functions which have been changed to newlib.. however we need to keep fileXioGetStat() as the newlib stat struct doesn't contain the start sector (AFAIK)

### CODE REVIEW

**Review by AKuHAK — APPROVED** [review]
So, strings are counted from 0 so the last should be NULL, not last+1. Now it looks correct - i was not sure if it were correct in the previous attempt.

**Comment by KrahJohlito** [comment]
Yea sorry I had a brain fart

**Comment by KrahJohlito** [comment]
im just gonna close this until the white screen issue is resolved as I may end up changing the same lines again anyway

**Comment by KrahJohlito** [comment]
Ok this is confirmed to fix #5, previously it didn't work due to the fileXio functions which have been changed to newlib.. however we need to keep fileXioGetStat() as the newlib stat struct doesn't contain the start sector (AFAIK)

**Comment by AKuHAK** [comment]
Huh, again +OPL as default partition.

**Comment by KrahJohlito** [comment]
That’s only if things fail.. if it can’t open __common, if it can’t find a conf_hdd.cfg, it a cfg is found but it is blank.. if any of those then use +OPL since that is the same as OPL logic.. some shouldn’t happen but may as well have a check in case.

**Pull request merged**
