### PR TITLE
Minor changes to readme

### PR DESCRIPTION
**Pull request by israpps**
## Pull Request checklist

Note: these are not necessarily requirements

- [ ] I reformatted the code with clang-format
- [ ] I checked to make sure my submission worked
- [ ] I am the author of submission or have permission from the original author
- [ ] Requires update of the PS2SDK
- [ ] Requires update of the gsKit
- [ ] Others (please specify below)

### CODE REVIEW

**Comment by KrahJohlito** [comment]
Some of this undoes the previous readme changes by @AKuHAK .. perhaps you two can discuss what to do here

**Comment by AKuHAK** [comment]
@KrahJohlito this pr is reverting just cosmetic changes.
@israpps Codacy doesn't like your PR, could you check what is wrong?

**Comment by israpps** [comment]
> @KrahJohlito this pr is reverting just cosmetic changes.
> @israpps Codacy doesn't like your PR, could you check what is wrong?

Quite odd...
if you take a look you'll see that i just changed sintax highlight on some code blocks and campacted Kelftool link...

**Comment by KrahJohlito** [comment]
@israpps Im not sure if you know but you can
git rebase -i origin branch name
and it will open a text window where you can squash commits, rename, drop etc etc (fix up is what you’d be looking for here IMO)

Then if you
git push -f
You will force push the changes, that way we don’t need to squash merge pull requests that have multiple commits essentially changing the same things. Hope this helps

Ps on my phone so I cant do code brackets for some reason.

**Comment by israpps** [comment]
> @israpps Im not sure if you know but you can
> git rebase -i origin branch name
> and it will open a text window where you can squash commits, rename, drop etc etc (fix up is what you’d be looking for here IMO)
> 
> Then if you
> git push -f
> You will force push the changes, that way we don’t need to squash merge pull requests that have multiple commits essentially changing the same things. Hope this helps
> 
> Ps on my phone so I cant do code brackets for some reason.

I'm on my phone too...
I only had 30 minutes in front of the laptop in the last 7 days (and i spent it on HDL Batch installer 3.0.0)

**Comment by AKuHAK** [comment]
@KrahJohlito Squash and merge?

**Comment by KrahJohlito** [comment]
Sure no problem, wasn't trying to be rude or anything just not sure how familiar you are with git... I used it for over a year before bothering to learn how to rebase, cherry-pick etc

**Pull request merged**
